<?php
  if(isset($_POST['kirim'])){
      $jalur = $_POST['jalur'];
      $nama_mhs = $_POST['nama_mhs'];
      $ttl = $_POST['ttl'];
      $nik = $_POST['nik'];
      $jk = $_POST['jk'];
      $agama = $_POST['agama'];
      $status = $_POST['status'];
      $alamat = $_POST['alamat'];
      $kodepos = $_POST['kodepos'];
      $noHp = $_POST['noHp'];
      $email = $_POST['email'];
      $asal_sekolah = $_POST['asal_sekolah'];
      $tahun_lulus = $_POST['tahun_lulus'];
      $nm_ayah = $_POST['nm_ayah'];
      $nm_ibu = $_POST['nm_ibu'];
      $alamat1 = $_POST['alamat1'];
      $kodepos1 = $_POST['kodepos1'];
      $no_Hp = $_POST['no_Hp'];
      $pnd_ayah = $_POST['pnd_ayah'];
      $pnd_ibu = $_POST['pnd_ibu'];
      $sta_ayah = $_POST['sta_ayah'];
      $sta_ibu = $_POST['sta_ibu'];
      $pk_ayah = $_POST['pk_ayah'];
      $pk_ibu = $_POST['pk_ibu'];
      $prodi1 = $_POST['prodi1'];
      $prodi2 = $_POST['prodi2'];
      $sumber = $_POST['sumber'];
      $gelombang = $_POST['gelombang']; 

      echo"Jalur Penerimaan Mahasiswa Baru * = ".$jalur;
      echo"<br>";
      echo"Nama Calon Mahasiswa (Sesuai Akte Kelahiran) * = ".$nama_mhs;
      echo"<br>";
      echo"Tempat & Tanggal Lahir * = ".$ttl;
      echo"<br>";
      echo"NIK(Nomor Induk Kependudukan KTP/KK) * = ".$nik;
      echo"<br>";
      echo"Jenis Kelamin = ".$jk;
      echo"<br>";
      echo"Agama * = ".$agama;
      echo"<br>";
      echo"Status * = ".$status;
      echo"<br>";
      echo"Alamat * = ".$alamat;
      echo"<br>";
      echo"Kode Pos * = ".$kodepos;
      echo"<br>";
      echo"No Handphone * = ".$noHp;
      echo"<br>";
      echo"Email * = ".$email;
      echo"<br>";
      echo"Asal Sekolah * = ".$asal_sekolah;
      echo"<br>";
      echo"Tahun Lulus * = ".$tahun_lulus;
      echo"<br>";
      echo"Nama Ayah * = ".$nm_ayah;
      echo"<br>";
      echo"Nama Ibu * = ".$nm_ibu;
      echo"<br>";
      echo"Alamat * = ".$alamat1;
      echo"<br>";
      echo"Kode Pos * = ".$kodepos1;
      echo"<br>";
      echo"No. Handphone * = ".$no_Hp;
      echo"<br>";
      echo"Pendidikan Terakhir Ayah * = ".$pnd_ayah;
      echo"<br>";
      echo"Pendidikan Terakhir Ibu * = ".$pnd_ibu;
      echo"<br>";
      echo"Status Ayah * = ".$sta_ayah;
      echo"<br>";
      echo"Status Ibu * = ".$sta_ibu;
      echo"<br>";
      echo"Pekerjaan Ayah * = ".$pk_ayah;
      echo"<br>";
      echo"Pekerjaan Ibu* = ".$pk_ibu;
      echo"<br>";
      echo"Pilihan Program Studi 1 = ".$prodi1;
      echo"<br>";
      echo"Pilihan Program Studi 2 = ".$prodi2;
      echo"<br>";
      echo"Sumber Informasi = ".$sumber;
      echo"<br>";
      echo"Pilihan Gelombang = ".$gelombang;
  }
?>